# Generated by Django 5.1.4 on 2025-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=150)),
                ('subscribed', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Contribute/Photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='Contribute/Videos/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='Contribute/PDFs/')),
            ],
        ),
    ]
