# Generated by Django 5.1.4 on 2025-01-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribute',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
