# Generated by Django 5.1.4 on 2025-01-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_jeevandarshansection_jeevandarshanimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_landing_movie',
            field=models.BooleanField(default=False, help_text='Check if this movie is for the landing page'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Check if this movie is recommended'),
        ),
    ]
