# Generated by Django 5.1.4 on 2025-01-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_movie_is_short_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipbook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='flipbooks/covers/'),
        ),
    ]
