# Generated by Django 5.1.4 on 2025-02-07 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_thematic_section_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeevandarshanimage',
            options={'ordering': ['id'], 'verbose_name': 'Jeevan Darshan Image', 'verbose_name_plural': 'Jeevan Darshan Images'},
        ),
        migrations.AlterModelOptions(
            name='jeevandarshansection',
            options={'verbose_name': 'Jeevan Darshan Section', 'verbose_name_plural': 'Jeevan Darshan Sections'},
        ),
        migrations.RenameField(
            model_name='jeevandarshansection',
            old_name='section_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='jeevandarshansection',
            old_name='section_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='jeevandarshanimage',
            name='image_description',
        ),
        migrations.RemoveField(
            model_name='jeevandarshanimage',
            name='image_title',
        ),
        migrations.AddField(
            model_name='jeevandarshanimage',
            name='short_description',
            field=models.TextField(default='left desctiopiton ', help_text='Short description for homepage display'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeevandarshanimage',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique slug for detail page URL', unique=True),
        ),
        migrations.AddField(
            model_name='jeevandarshanimage',
            name='title',
            field=models.CharField(default='title for test', help_text='Title for the philosophy/image', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jeevandarshanimage',
            name='image',
            field=models.ImageField(help_text='Image for the philosophy', upload_to='jeevan_darshan/'),
        ),
        migrations.CreateModel(
            name='JeevanDarshanPhilosophyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_description', models.TextField(help_text='Left side description for the philosophy')),
                ('right_description', models.TextField(help_text='Right side description for the philosophy')),
                ('image', models.OneToOneField(help_text='Philosophy details associated with the image', on_delete=django.db.models.deletion.CASCADE, related_name='philosophy_info', to='home.jeevandarshanimage')),
            ],
            options={
                'verbose_name': 'Jeevan Darshan Philosophy Info',
                'verbose_name_plural': 'Jeevan Darshan Philosophy Infos',
            },
        ),
    ]
