# Generated by Django 5.1.4 on 2025-02-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_jeevandarshansection_coffee_table_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeevandarshansection',
            name='coffee_table_book',
        ),
        migrations.RemoveField(
            model_name='jeevandarshansection',
            name='thematic',
        ),
        migrations.AddField(
            model_name='jeevandarshansection',
            name='related_coffee_table_book',
            field=models.ForeignKey(blank=True, help_text='Select a related Coffee Table Book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jeevan_darshan_sections', to='home.coffeetablebook'),
        ),
        migrations.AddField(
            model_name='jeevandarshansection',
            name='related_thematic',
            field=models.ForeignKey(blank=True, help_text='Select a related Thematic book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jeevan_darshan_sections', to='home.thematic'),
        ),
    ]
