# Generated by Django 5.1.4 on 2025-02-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_thematic_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeetablebook',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='Coffee Table Book/'),
        ),
    ]
