# Generated by Django 5.1.4 on 2025-02-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_flipbook_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flipbook',
            old_name='file',
            new_name='book_pdf',
        ),
    ]
