# Generated by Django 5.1.4 on 2025-02-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_file_flipbook_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='fifth_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='fifth_discripton_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_project/'),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='first_discripton',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='first_discripton_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_project/'),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='fourth_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='fourth_discripton_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_project/'),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='long_discripton',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='second_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='second_discripton_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_project/'),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='sixth_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='sixth_discripton_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_project/'),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='third_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='third_discripton_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_project/'),
        ),
    ]
