# Generated by Django 5.1.6 on 2025-02-20 06:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_aboutproject_fifth_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproject',
            name='description_left',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='description_right',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='fifth_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='first_discripton',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='fourth_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='long_discripton',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='second_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='sixth_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='third_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutprojectimage',
            name='alt_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffeetablebook',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='flipbook',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jeevandarshanimage',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='Short description for homepage display'),
        ),
        migrations.AlterField(
            model_name='jeevandarshansection',
            name='left_description',
            field=ckeditor.fields.RichTextField(help_text='Left side description for the philosophy'),
        ),
        migrations.AlterField(
            model_name='jeevandarshansection',
            name='right_description',
            field=ckeditor.fields.RichTextField(help_text='Right side description for the philosophy'),
        ),
        migrations.AlterField(
            model_name='jeevandarshansection',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='Short description for homepage display'),
        ),
        migrations.AlterField(
            model_name='landingpagesection',
            name='additional_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Extra content (e.g., paragraph for Jeevan Darshan)'),
        ),
        migrations.AlterField(
            model_name='landingpagesection',
            name='long_description',
            field=ckeditor.fields.RichTextField(help_text='Detailed description for the section'),
        ),
        migrations.AlterField(
            model_name='landingpagesection',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='Brief summary (1-2 sentences)'),
        ),
    ]
