# Generated by Django 5.1.4 on 2025-01-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=100)),
                ('description_left', models.TextField()),
                ('description_right', models.TextField()),
                ('logo_image', models.ImageField(upload_to='about_project/')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeTableBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_table_book_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('book_pdf', models.FileField(upload_to='Coffee Table Book/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='Coffee Table Book/Covers/')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero1', 'Iks Gyan Gunjan'), ('hero2', '100 Regions'), ('hero3', 'Jeevan Darshan')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('additional_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the movie', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A short description of the movie')),
                ('youtube_link', models.URLField(blank=True, help_text='YouTube link for the movie. Leave blank if the movie is directly uploaded.', null=True)),
                ('uploaded_movie', models.FileField(blank=True, help_text='Upload the movie file directly if not available on YouTube.', null=True, upload_to='movies/')),
                ('movie_thumbnail', models.ImageField(blank=True, help_text='Thumbnail for the movie', null=True, upload_to='movie_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=255)),
                ('cover_picture', models.ImageField(upload_to='Thematic/')),
            ],
        ),
        migrations.CreateModel(
            name='LandingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landingImages/')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('shape', models.CharField(blank=True, max_length=50)),
                ('rotation', models.CharField(blank=True, max_length=50)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.landingpagedata')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='home.state')),
            ],
        ),
        migrations.CreateModel(
            name='Flipbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='flipbooks/')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flipbooks', to='home.region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipbooks', to='home.state')),
            ],
        ),
    ]
