# Generated by Django 5.1.4 on 2025-01-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=150)),
                ('Contribute_type', models.CharField(choices=[('Media', 'Media'), ('Content', 'Content')], default='Content', max_length=200)),
                ('message', models.TextField()),
                ('media', models.ImageField(upload_to='Contribute/')),
            ],
        ),
    ]
