# Generated by Django 5.1.4 on 2025-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_landingpagedata_landingimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribute',
            name='Contribute_type',
        ),
        migrations.RemoveField(
            model_name='contribute',
            name='media',
        ),
        migrations.AddField(
            model_name='contribute',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='Contribute/PDFs/'),
        ),
        migrations.AddField(
            model_name='contribute',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Contribute/Photos/'),
        ),
        migrations.AddField(
            model_name='contribute',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contribute',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Contribute/Videos/'),
        ),
        migrations.AlterField(
            model_name='contribute',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
