# Generated by Django 5.1.4 on 2025-01-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contribute_contribute_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the movie', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A short description of the movie')),
                ('youtube_link', models.URLField(blank=True, help_text='YouTube link for the movie. Leave blank if the movie is directly uploaded.', null=True)),
                ('uploaded_movie', models.FileField(blank=True, help_text='Upload the movie file directly if not available on YouTube.', null=True, upload_to='movies/')),
            ],
        ),
    ]
