# Generated by Django 5.1.4 on 2025-01-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribute',
        ),
    ]
