# Generated by Django 5.1.4 on 2025-01-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_contribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeTableBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_table_book_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('book_pdf', models.FileField(upload_to='Coffee Table Book/')),
            ],
        ),
    ]
