# Generated by Django 5.1.4 on 2025-01-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_state_region_flipbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='about_project/images/')),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=100)),
                ('description_left', models.TextField()),
                ('description_right', models.TextField()),
                ('logo_image', models.ImageField(upload_to='about_project/')),
                ('images', models.ManyToManyField(to='home.projectimage')),
            ],
        ),
    ]
