# Generated by Django 5.1.4 on 2025-01-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_projectimage_aboutproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutproject',
            name='images',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
