# Generated by Django 5.1.4 on 2025-02-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_jeevandarshanimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeevandarshanimage',
            name='slug',
        ),
    ]
