# Generated by Django 5.1.4 on 2025-02-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_jeevandarshansection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeevandarshansection',
            name='coffee_table_book',
            field=models.ForeignKey(blank=True, help_text='Related Coffee Table Book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.coffeetablebook'),
        ),
        migrations.AddField(
            model_name='jeevandarshansection',
            name='thematic',
            field=models.ForeignKey(blank=True, help_text='Related Thematic Book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.thematic'),
        ),
    ]
