# Generated by Django 5.1.4 on 2025-02-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_coffeetablebook_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='flipbooks/'),
        ),
    ]
